version: "3.8"
services:
  nest-api:
    container_name: nest-api
    env_file:
      - ./packages/backend/.env
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

    volumes:
      - ./packages/backend:/usr/src/app # Mount the current directory to the workdir in the container
      # - /usr/src/app/node_modules # Use a Docker volume for node_modules to avoid overwriting with the local node_modules

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./packages/backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data

  prisma-studio:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: prisma-studio
    ports:
      - "5555:5555"
    build:
      context: ./packages/backend/prismaStudio
      dockerfile: Dockerfile
    env_file:
      - ./packages/backend/.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./packages/backend/prisma:/app/prisma

volumes:
  postgres:
    name: nest-db
